#!/bin/bash
# Set up ESPHome dev environment

set -e

cd "$(dirname "$0")/.."

python3 -m venv venv
source venv/bin/activate

# Avoid unsafe git error when running inside devcontainer
if [ -n "$DEVCONTAINER" ];then
  git config --global --add safe.directory "$PWD"
fi

pip3 install esphome

script/platformio_install_deps.py platformio.ini --libraries --tools --platforms
